platform: linux
inputs:
 - name: ccp_src
 - name: cluster_env_files
 - name: gpdb_binary
run:
  path: bash
  args:
  - -c
  - |
    set -ex
    ccp_src/scripts/setup_ssh_to_cluster.sh
    ssh centos@mdw "sudo bash -c \"yum --cacheonly list installed mailx valgrind\""
    ssh -t mdw "bash /home/gpadmin/gpdb_src/concourse/scripts/create_demo_cluster.sh"
